version: "3.4"
services:
  frontend:
    image: ghcr.io/kaeyros-analytics/tdd-flask/tdd-frontend:latest
    ports:
      - "3000:3000"
  backend:
    image: ghcr.io/kaeyros-analytics/tdd-flask/tdd-backend:latest
    ports:
      - "5000:5000"
networks:
  host:
    name: host
    external: true